name: Auto Merge

on:
  # Wird ausgelöst, wenn ein Pull Request geöffnet wird
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      # Benötigt Berechtigungen, um Pull Requests zu verwalten
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge for Action PRs
        # Dieser Schritt wird NUR ausgeführt, wenn der Ersteller des PRs die GitHub Action selbst ist
        if: github.actor == 'github-actions[bot]'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          # Verwendet "squash" um alle Commits des PRs zu einem einzigen zusammenzufassen
          merge-method: squash
